import { defineConfig } from "tsup";

export default defineConfig({
  entry: ["src/index.ts", "src/commands/**/*.ts"],
  format: ["cjs"],
  dts: true,
  splitting: false,
  sourcemap: true,
  clean: true,
  outDir: "lib",
  target: "node18",
  external: [
    "@inquirer/prompts",
    "@oclif/command",
    "@oclif/config",
    "@oclif/plugin-help",
    "adm-zip",
    "archiver",
    "chokidar",
    "cors",
    "express",
    "fast-glob",
    "ignore",
    "keytar",
    "listr2",
    "node-pty",
    "open",
    "ora",
    "p-limit",
    "tslib",
    "update-notifier",
    "ws",
    "zod",
  ],
  banner: {
    js: "#!/usr/bin/env node",
  },
});
