name: CI

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  FORCE_COLOR: 3
  NODE_OPTIONS: "--max-old-space-size=8192"
  TURBO_FORCE: ${{ contains(github.event.pull_request.labels.*.name, 'disable cache') && 'true' || '' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Turbo cache
        uses: actions/cache@v4
        with:
          path: .turbo
          key: turbo-${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            turbo-${{ runner.os }}-build-

      - name: Build api types
        run: pnpm --filter @tutly/api trpc-api-export

      - name: Upload api types
        uses: actions/upload-artifact@v4
        with:
          name: api-types
          path: |
            apps/api/trpc-api-export/dist
            apps/api/package.json

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Download api types
        uses: actions/download-artifact@v4
        with:
          name: api-types
          path: apps/api

      - name: Setup
        uses: ./tooling/github/setup

      - name: Turbo cache
        uses: actions/cache@v4
        with:
          path: .turbo
          key: turbo-${{ runner.os }}-lint-${{ github.sha }}
          restore-keys: |
            turbo-${{ runner.os }}-lint-

      - name: Copy env
        shell: bash
        run: cp .env.example .env

      - name: Lint with Turbo
        run: pnpm lint

      - name: Lint workspace
        run: pnpm lint:ws

  format:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup

      - name: Turbo cache
        uses: actions/cache@v4
        with:
          path: .turbo
          key: turbo-${{ runner.os }}-format-${{ github.sha }}
          restore-keys: |
            turbo-${{ runner.os }}-format-

      - name: Format
        run: pnpm format

  typecheck:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Download api types
        uses: actions/download-artifact@v4
        with:
          name: api-types
          path: apps/api

      - name: Setup
        uses: ./tooling/github/setup

      - name: Turbo cache
        uses: actions/cache@v4
        with:
          path: .turbo
          key: turbo-${{ runner.os }}-typecheck-${{ github.sha }}
          restore-keys: |
            turbo-${{ runner.os }}-typecheck-

      - name: Typecheck
        run: pnpm typecheck
