name: Deploy Web App to Production

env:
  TURBO_FORCE: ${{ github.event_name == 'workflow_dispatch' && contains(github.event.inputs.labels, 'disable cache') && 'true' || '' }}

on:
  push:
    branches:
      - main
    paths:
      - "apps/web/**"
      - "packages/**"
      - "tooling/**"
      - "turbo/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - "turbo.json"
  workflow_dispatch:

jobs:
  Deploy-Web-Production:
    name: Deploy Web App to Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Production
        id: deploy
        run: |
          echo "🚀 Deploying to Production..."

          # Trigger deployment via webhook
          RESPONSE=$(curl --request GET "${COOLIFY_WEBHOOK_WEB}" \
            --header "Authorization: Bearer ${COOLIFY_TOKEN}" \
            --silent --show-error --fail)

          if [ $? -eq 0 ]; then
            echo "✅ Deployment triggered successfully"
            echo "Response: $RESPONSE"
            echo "deployment_status=success" >> $GITHUB_OUTPUT
          else
            echo "❌ Deployment failed"
            echo "Response: $RESPONSE"
            exit 1
          fi
        env:
          COOLIFY_WEBHOOK_WEB: ${{ secrets.COOLIFY_WEBHOOK_WEB }}
          COOLIFY_TOKEN: ${{ secrets.COOLIFY_TOKEN }}
